export default [
    { abbreviation: 'alf', name: 'alpha' },
    { abbreviation: 'bet', name: 'beta' },
    { abbreviation: 'gam', name: 'gamma' },
    { abbreviation: 'del', name: 'delta' },
    { abbreviation: 'eps', name: 'epsilon' },
    { abbreviation: 'zet', name: 'zeta' },
    { abbreviation: 'eta', name: 'eta' },
    { abbreviation: 'tet', name: 'theta' },
    { abbreviation: 'iot', name: 'iota' },
    { abbreviation: 'kap', name: 'kappa' },
    { abbreviation: 'lam', name: 'lambda' },
    { abbreviation: 'mu.', name: 'mu' },
    { abbreviation: 'nu.', name: 'nu' },
    { abbreviation: 'ksi', name: 'xi' },
    { abbreviation: 'omi', name: 'omicron' },
    { abbreviation: 'pi.', name: 'pi' },
    { abbreviation: 'rho', name: 'rho' },
    { abbreviation: 'sig', name: 'sigma' },
    { abbreviation: 'tau', name: 'tau' },
    { abbreviation: 'ups', name: 'upsilon' },
    { abbreviation: 'phi', name: 'phi' },
    { abbreviation: 'chi', name: 'chi' },
    { abbreviation: 'psi', name: 'psi' },
    { abbreviation: 'ome', name: 'omega' }
]
